spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/progetto_medusa
    username: admin
    password: admin123
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com:
     progettomedusa: DEBUG

security:
  licensed-apps:
    - local-postman
    - 9110e2a42e28b6cf56f7bc507753c1d76a60f3bbd209ed1da9eb6071b36d14a9

mail-service:
  url: http://localhost:8082